import Head from 'next/head'

// 추후 next-seo로 변경 
// https://www.npmjs.com/package/next-seo

const Seo = ()=>(
  <Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
    <link rel="stylesheet" href="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.3.2/build/styles/default.min.css"></link>
  </Head>
)

export default Seo;