import Head from 'next/head'

// 추후 next-seo로 변경 
// https://www.npmjs.com/package/next-seo

const Seo = ()=>(
  <Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
)

export default Seo;